# Generated by Django 4.0.5 on 2022-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='edad',
            field=models.PositiveBigIntegerField(),
        ),
    ]
